### ISSUE TITLE
Issues while loading some URLs.

### ISSUE THREAD

**Issue by cfviotti** [simplesconsultoria/sc.embedder#11]
We're using embedder on Portal Modelo (https://github.com/interlegis/portalmodelo) and when we load Flickr sets URLs, for example, we receive a collective.oembed "404 not found" error message in our log, though the link works ok on the browser. And this apparently happens only with URL from sets, but not single photos, these will work fine.
e.g:
http://www.flickr.com/photos/albionharrisonnaish/14436191205/in/set-72157642936095895 (Loads fine)
http://www.flickr.com/photos/albionharrisonnaish/sets/72157642936095895/ (Won't load)
Could this be sc.embedder using an old oembed version or anything like that?

Also, it won't work with HTTPS (which normally IS in the regular URL the user will copy from the address bar), collective.oembed says: "There are no endpoints available for [URL with https]". And by the way, this message is only displayed in our log. There is no cue on the front-end so the end user may understand what is happening.

Last but not least, we get a Plone ValueError: unknown url type, when we ommit HTTP:// or HTTPS:// from the url. Like this: http://pastebin.com/nLpQZVW3

I understand these problems might be slightly different, though I think it may be fine to open only one issue to address them. If not, I can open it separately too.

**Comment by hvelarde** [comment]
@jeanferri, any news on this?

**Comment by cfviotti** [comment]
@hvelarde, nothing new until now, I've opened separated tickets for each problem and simplified the description.

**Comment by hvelarde** [comment]
all problems reported have now an individual issue.
