### ISSUE TITLE
AttributeError: getPrimaryField (when products collective.oembed and plone.app.contenttypes are installed)

### ISSUE THREAD

**Issue by idgserpro** [simplesconsultoria/sc.embedder#12]
Steps to reproduce:

- Create a Plone Site and install the products: sc.embedder, collective.oembed and plone.app.contenttypes
- Add a file.
- Access the url: http://site-url/@@oembed&url=http:/file-url&format=json

Error:

    Traceback (innermost last):

        Module ZPublisher.Publish, line 138, in publish
        Module ZPublisher.mapply, line 77, in mapply
        Module ZPublisher.Publish, line 48, in call_object
        Module collective.oembed.provider, line 37, in __call__
        Module collective.oembed.provider, line 79, in update
        Module collective.oembed.provider, line 98, in build_info
    
    AttributeError: getPrimaryField 

This is because collective.oembed<2.0a1 is not compatible with dexterity content (in provider). This has been fixed in version 2.0 of collective.oembed in:

https://github.com/collective/collective.oembed/commit/d8f1f919a1d1e9ece078c5ff44466b6bee96337f#diff-c0682f1dd061d568559a98c175590c68

However, sc.embedder want collective.oembed<2.0a1 in commit's @hvelarde:

https://github.com/simplesconsultoria/sc.embedder/commit/c05e25067e006d1960c5ecc34ad723ceef0d580e

**Comment by hvelarde** [comment]
we are using collective.oembed in this package not to use all the features but only to load oembed data from the sites. removing the pinning is not that easy because collective.oembed 2.0 needs to be installed to work.

I think we should get rid fully from this dependency instead removing the pinning.
