### ISSUE TITLE
Remove dependency on collective.oembed

### ISSUE THREAD

**Issue by hvelarde** [simplesconsultoria/sc.embedder#13]
To avoid problems like the one reported on #12.

We need to find out a well maintained Python library for this as [python-oembed](https://pypi.python.org/pypi/python-oembed) seems to be abandoned.

**Comment by hvelarde** [comment]
@jeanferri @cfviotti could you please help me on selecting the right library for this?

**Comment by idgserpro** [comment]
@hvelarde remove the dependency of the collective.oembed is the best solution? Newer versions of collective.oembed support multiple sites. It would be no efforts division? Would not it be better to create compatibility with new versions of the collective.oembed?

**Comment by hvelarde** [comment]
the goal of this package is not to offer oEmbed support for a Plone site, but to add a content type that allow a user to embed multimedia content on a Plone object; we use oEmbed just as a standard mechanism to get information from a variety of providers.

let's keep things simpler and easy to understand and maintain.

**Comment by djowett** [comment]
@hvelarde A passing suggestion on this point.... (I'm choosing your repo as a location for one of my brain dumps again ;-) )
From a little look around I would give a vote to http://pyembed.github.io/ it seems to be well structured, modern, fairly up to date and they respond warmly to the suggestion of making a "Discoverer" based on http://oembed.com/providers.json   (see my Issue at https://github.com/pyembed/pyembed/issues/46).

For your (and my) usecase I don't see a need for cluttering the Zope component registry with oembed providers as collective.oembed does.

The simple example:

    >>> html = PyEmbed().embed('https://vimeo.com/135235106', max_width=640)
    >>> html
    u'<iframe src="https://player.vimeo.com/video/135235106" width="640" height="360" frameborder="0" title="borg video" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'

Generating a thumbnail took a bit more figuring out:

    from pyembed.core.render import DefaultRenderer

    class ThumbnailRenderer(DefaultRenderer):
        """Thumbnail Renderer for videos.
        """
        RENDERER = '<img src="%(thumbnail_url)s" width="%(width)s" height="%(height)s" />'
        def render(self, content_url, response):
            params = dict(response.__dict__)
            params['content_url'] = content_url
            if response.type == 'video':
                return self.RENDERER % params
            else:
                return super(ThumbnailRenderer, self).render(content_url, response)

    >>> html = PyEmbed(renderer=ThumbnailRenderer()).embed('https://vimeo.com/135235106', max_width=640)
    >>> html
    u'<img src="https://i.vimeocdn.com/video/529083386_640.jpg" width="640" height="360" />'

**Comment by hvelarde** [comment]
@djowett nice discovery! yes, we can update this package using that.

feel free to open a branch ;-) we are way busy now with 2 other sites coming out of the oven.

**Comment by djowett** [comment]
Update: my suggestion got implemented (quickly too), so pyembed looks seriously polished now IMO.  
Note: I was advised (in that same issue) I didn't need the ThumbnailRenderer above, but I'm not so sure.

I will feel free to branch, thanks, but it's unlikely in the near future.
