### ISSUE TITLE
Image not traversable via @@images api

### ISSUE THREAD

**Issue by simahawk** [simplesconsultoria/sc.embedder#15]
You cannot access image view `/@@images/image/SCALE_NAME`.
Is this a feature? If so, how to get public url for image field without using `tag` method?

**Comment by hvelarde** [comment]
I just test it and it works as you can see below:

![imagem da pagina 2015-03-02 - 16 38 03](https://cloud.githubusercontent.com/assets/341393/6448697/8fef0cd2-c0fa-11e4-8502-43ec1dca0057.png)

this image was generated by using **obj/@@images/image/preview**.

**Comment by simahawk** [comment]
Strange, yesterday I tried by uploading and image manually and was not working. Tried right now w/ "load" button that loads the image properly and it's working.... sorry to have bothered you :S

**Comment by hvelarde** [comment]
no problem :beer:
