### ISSUE TITLE
Embedder won't load Flickr sets URLs.

### ISSUE THREAD

**Issue by cfviotti** [simplesconsultoria/sc.embedder#19]
Whenever we paste a Flickr set (album) URL and click on "Load", it fails to do so, while outputting a **collective.oembed "404 not found"** message in our foreground log. 
Though it will work fine if we paste a single photo URL. Eg:
>http://www.flickr.com/photos/albionharrisonnaish/14436191205/in/set-72157642936095895
 
^ Loads fine
>http://www.flickr.com/photos/albionharrisonnaish/sets/72157642936095895/ 

^ Won't load

**Comment by cfviotti** [comment]
It seems Flickr stopped supporting its embedded slideshow option, and now is quite obscured in how to get the code. You can access their Flash slideshow by appending "/show" in any sets URL, and find the code clicking in share, on the top-right corner. You must also be logged in on Flickr for it to work.

You can check it in the same set used as example above:
>http://www.flickr.com/photos/albionharrisonnaish/sets/72157642936095895/show

**Comment by hvelarde** [comment]
you can get the oEmbed from a set like this:

https://www.flickr.com/services/oembed/?url=http://www.flickr.com/photos/albionharrisonnaish/sets/72157642936095895/show

this seems to be related with #13
