### ISSUE TITLE
URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:581)>

### ISSUE THREAD

**Issue by idgserpro** [simplesconsultoria/sc.embedder#21]
The openssl 1.0.1 [added support to TLS 1.1 and TLS 1.2](https://www.openssl.org/news/openssl-1.0.1-notes.html). However, [python 2 don't have support for TLS 1.1 / TLS 1.2](https://bugs.python.org/issue16692).

In OS's that use the openssl 1.0.1 and enable support for TLS 1.1 / 1.2, like Red Hat 7, occurs an error  'URLError' when the python 2 need to use TLS.

When filled the 'Multimedia URL' field with a url 'https' and click on 'Load', occurs:

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module plone.z3cform.layout, line 66, in __call__
    Module plone.z3cform.layout, line 50, in update
    Module plone.dexterity.browser.add, line 112, in update
    Module plone.z3cform.fieldsets.extensible, line 59, in update
    Module plone.z3cform.patch, line 30, in GroupForm_update
    Module z3c.form.group, line 141, in update
    Module plone.app.z3cform.csrf, line 21, in execute
    Module z3c.form.action, line 98, in execute
    Module z3c.form.button, line 315, in __call__
    Module z3c.form.button, line 170, in __call__
    Module sc.embedder.content.embedder, line 302, in handleLoad
    Module sc.embedder.content.embedder, line 232, in load_oembed
    Module sc.embedder.content.embedder, line 219, in get_fallback
    Module urllib2, line 431, in open
    Module urllib2, line 449, in _open
    Module urllib2, line 409, in _call_chain
    Module urllib2, line 1240, in https_open
    Module urllib2, line 1197, in do_open

    URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:581)> 

One way to fix this problem:

https://github.com/svalgaard/fskintra/issues/15

**Comment by hvelarde** [comment]
I think this is not an issue of this package and I don't want to implement that fix on it.

take a look at https://pypi.python.org/pypi/backports.ssl and let me know if that works.

then we can just document that on the README.

**Comment by idgserpro** [comment]
The problem was occurring because the proxy was blocking youtube.
