### ISSUE TITLE
PicklingError: Can't pickle <class 'collective.oembed.interfaces.OEmbedLayer'>: import of module collective.oembed.interfaces failed 

### ISSUE THREAD

**Issue by idgserpro** [simplesconsultoria/sc.embedder#38]
The sc.embedder 1.0b3 [requires collective.oembed](https://github.com/simplesconsultoria/sc.embedder/blob/1.0b3/setup.py#L55). The sc.embedder 1.0b4 [removed this dependency](https://github.com/simplesconsultoria/sc.embedder/commit/cdb900c731df61d8103225151c6a8d516ad6650f). On sites that have sc.embedder 1.0b3 and collective.oembed installed  and then were upgraded to sc.embedder 1.0b4, the collective.oembed is not added when running buildout. So, when we try install a product in controlpanel the error occurs:

    Traceback (innermost last):

        Module ZPublisher.Publish, line 146, in publish
        Module Zope2.App.startup, line 301, in commit
        Module transaction._manager, line 89, in commit
        Module transaction._transaction, line 329, in commit
        Module transaction._transaction, line 443, in _commitResources
        Module ZODB.Connection, line 567, in commit
        Module ZODB.Connection, line 623, in _commit
        Module ZODB.Connection, line 658, in _store_objects
        Module ZODB.serialize, line 422, in serialize
        Module ZODB.serialize, line 431, in _dump

    PicklingError: Can't pickle <class 'collective.oembed.interfaces.OEmbedLayer'>: import of module collective.oembed.interfaces failed

It would be interesting to have a upgrade step that fix this problem if the collective.oembed is not available.

**Comment by hvelarde** [comment]
IMO this has nothing to do with sc.embedder; if you installed collective.oembed in your site you will have to manually add it into your buildout as a dependency.

**Comment by idgserpro** [comment]
In fact, I don't installed collective.oembed. I just run your [upgrade step](https://github.com/collective/collective.oembed/blob/master/collective/oembed/upgrades.zcml#L7). This upgrade installed your profile. My site only had collective.oembed because of sc.embedder. I don't want the collective.oembed on my site. This is preventing the update of brasil.gov.portal.

**Comment by hvelarde** [comment]
can you point the code on this package where the installation of collective.oembed takes place?

the upgrade step mentioned above is on colective.oembed and not here.

**Comment by idgserpro** [comment]
sc.embedder had collective.oembed as a dependency in older versions. Because of that, an upgradeStep for collective.oembed was shown in portal_setup and executed.

So, somewhere between all releases of sc.embedder, you added collective.oembed that now is removed.

We agree that this is not a direct sc.embedder error, but because you add it as a dependency and removed afterwards, we believe it's sc.embedder reponsibility to make an upgradeStep to fix it. It doesn't make sense to fix in collective.oembed since it's not a dependency anymore.

**Comment by hvelarde** [comment]
sorry guys, but I don't agree: yes, collective.oembed was a dependency of this package but that error can only happen if it was installed at some point and then the egg removed; we never installed it explicitly then you can't blame this package for that error.

as I said before, just add the egg to the buildout and uninstall the package if you're not using it any more.

**Comment by idgserpro** [comment]
@hvelarde , unfortunately it's not that simple.

The collective.oembed [doesn't have an uninstall profile](https://github.com/collective/collective.oembed/tree/master/collective/oembed/profiles).

**Comment by idgserpro** [comment]
> but that error can only happen if it was installed at some point and then the egg removed

You (sc.embedder) never installed it explicitly but explicitly added it as a dependency. The upgradeStep from collective.oembed was executed, and now sc.embedder removed the egg. If the upgradeStep from this package wasn't supposed to be executed, than a warning should have been in sc.embedder's README, stating "don't install since we're only using a python dependency from this package".

**Comment by hvelarde** [comment]
can you explain me why and how the upgrade step of collective.oembed was executed if the package was not installed?

**Comment by idgserpro** [comment]
If you have collective.oembed in eggs, an [upgrade step](https://github.com/collective/collective.oembed/blob/master/collective/oembed/upgrades.zcml#L7) will be shown, even without the product be installed.

In fact, I don't know if the collective.oembed was installed or not, because the brasil.gov.portal [hide it from portal_quickinstaller](https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/config.py#L148).

**Comment by hvelarde** [comment]
no, you have to manually fix all the installations because **you** ran an upgrade step of a package that was not installed and you are completely responsible for that.

no problem, shit happens all the time and you can face that as an opportunity to learn new things. next time be careful and keep in mind that there's no reason to do such things.

here is some sample code you can use to write an upgrade step to fix the issue:

```python
from plone.browserlayer.utils import unregister_layer
unregister_layer('xyz')
```
