### ISSUE TITLE
Error in TinyMCE plugin if the property icon_visibility is disabled.

### ISSUE THREAD

**Issue by idgserpro** [simplesconsultoria/sc.embedder#42]
If property ```portal_properties/site_properties/icon_visibility``` is disabled, and created a Embedder, after when we add a document, clicking in sc.embedder button in TinyMCE, and so click in current folder, the js error occurs:

```javascript
TypeError: data.items[i].icon is null

if (data.items[i].icon.length) {

scembedder.js (line 452)
```
Then, the folder contents are not listed.

The line in question is [this](https://github.com/simplesconsultoria/sc.embedder/blob/master/src/sc/embedder/skins/tinymce/scembedder/js/scembedder.js#L452).

A fix is necessary like [here](https://github.com/simplesconsultoria/sc.embedder/commit/935a4e71534da2e9b86dc692497ea1169accd39e).

**Comment by idgserpro** [comment]
Description edited to say that the problem occurs even if you create a Embedder with image.

**Comment by idgserpro** [comment]
Related: https://github.com/simplesconsultoria/sc.embedder/issues/16

**Comment by hvelarde** [comment]
@idgserpro are you going to fix this?

**Comment by idgserpro** [comment]
@hvelarde unfortunately I have other priorities now. I can't do that now. But the fix is simple.

**Comment by hvelarde** [comment]
@idgserpro I think we can take care of it.
