### ISSUE TITLE
Validate iframe for obsolete attributes

### ISSUE THREAD

**Issue by hvelarde** [simplesconsultoria/sc.embedder#44]
There are a bunch of attributes that should not be included on `<iframes>` (because they are [obsolete](https://html.spec.whatwg.org/multipage/obsolete.html#non-conforming-features)) but some sites continue to use instead of deprecate.

We should validate the input to avoid users including the following attributes:

- align
- allowtransparency
- datafld
- datasrc
- frameborder
- framespacing
- hspace
- longdesc
- marginheight
- marginwidth
- scrolling
- vspace

Refs. #8

**Comment by hvelarde** [comment]
@idgserpro comments?

**Comment by rodfersou** [comment]
I think this should not be a validation, instead we should parse the provided html and remove automatically these attributes.

Also should take a look into [this old pull request](https://github.com/simplesconsultoria/sc.embedder/pull/9/files) that did something similar, but was rejected.

**Comment by idgserpro** [comment]
I think it should be done.

Although of Plone remove tags not allowed without warn the user, I think it is clearer to the user if use the validation. And it will be easier to implement.
